CREATE TABLE `USER`(
    `USER_ID` INT AUTO_INCREMENT NOT NULL,
    `USER_NAME` VARCHAR(255) NOT NULL,
    `PASSWORD` INT NOT NULL,
    `FULL_NAME` VARCHAR(255) NOT NULL,
    `ROLE` int(1) NOT NULL,
    CONSTRAINT `PRIMARY` PRIMARY KEY (`USER_ID`)
);
CREATE TABLE `POST`(
    `POST_ID` INT AUTO_INCREMENT NOT NULL,
    `POST_NAME` VARCHAR(255) NOT NULL,
    `POST_CONTENT` VARCHAR(255) NOT NULL,
    `USERID` INT NOT NULL,
    CONSTRAINT `PRIMARY` PRIMARY KEY (`POST_ID`)
);

CREATE TABLE `COMMENT`(
    `COMMENT_ID` INT AUTO_INCREMENT NOT NULL,
    `COMMENT_CONTENT` VARCHAR(255) NOT NULL,
    `USERID` INT NOT NULL,
    CONSTRAINT `PRIMARY` PRIMARY KEY (`COMMENT_ID`)
);

CREATE TABLE `COMMENT_POST`(
    `COMMENTID` INT NOT NULL,
    `POSTID` INT NOT NULL
); 
ALTER TABLE `COMMENT_POST` ADD CONSTRAINT FOREIGN KEY (`COMMENTID`) REFERENCES `COMMENT` (`COMMENT_ID`);
ALTER TABLE `COMMENT_POST` ADD CONSTRAINT FOREIGN KEY (`POSTID`) REFERENCES `POST` (`POST_ID`);
ALTER TABLE `POST` ADD CONSTRAINT FOREIGN KEY (`USERID`) REFERENCES `USER` (`USER_ID`);
ALTER TABLE `COMMENT` ADD CONSTRAINT FOREIGN KEY (`USERID`) REFERENCES `USER` (`USER_ID`);
 


