CREATE TABLE `comment` ( 
  `COMMENT_ID` INT AUTO_INCREMENT NOT NULL,
  `COMMENT_CONTENT` VARCHAR(255) NOT NULL,
  `USERID` INT NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`COMMENT_ID`)
);
CREATE TABLE `comment_post` ( 
  `COMMENTID` INT NOT NULL,
  `POSTID` INT NOT NULL
);
CREATE TABLE `post` ( 
  `POST_ID` INT AUTO_INCREMENT NOT NULL,
  `POST_NAME` VARCHAR(255) NOT NULL,
  `POST_CONTENT` VARCHAR(255) NOT NULL,
  `USERID` INT NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`POST_ID`)
);
CREATE TABLE `user` ( 
  `USER_ID` INT AUTO_INCREMENT NOT NULL,
  `USER_NAME` VARCHAR(255) NOT NULL,
  `PASSWORD` INT NOT NULL,
  `FULL_NAME` VARCHAR(255) NOT NULL,
  `ROLE` INT NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`USER_ID`)
);
ALTER TABLE `comment` ADD CONSTRAINT `comment_ibfk_1` FOREIGN KEY (`USERID`) REFERENCES `user` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `comment_post` ADD CONSTRAINT `comment_post_ibfk_1` FOREIGN KEY (`COMMENTID`) REFERENCES `comment` (`COMMENT_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `comment_post` ADD CONSTRAINT `comment_post_ibfk_2` FOREIGN KEY (`POSTID`) REFERENCES `post` (`POST_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `post` ADD CONSTRAINT `post_ibfk_1` FOREIGN KEY (`USERID`) REFERENCES `user` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
